# not sure how to fix the cut-and-paste between Windows and Linux here.
# Effectively we have two separate config files.

# Linux config

package: conda_kapsel

platform: linux-64

engine:
  - python=3.5

install:
  - conda install -y -q pip
  - pip install coverage flake8 pep257 pytest pytest-cov yapf==0.6.2 beautifulsoup4 tornado pytest-xdist
  - conda install -y -q redis pycrypto bcrypt ipython-notebook bokeh libffi ruamel_yaml anaconda-client requests
  - conda install -y -q -c conda-forge keyring

test:
  - LANG=en_US.UTF-8 python setup.py test

# windows is commented out because something is wrong with
# the build workers

# --- # Windows config starts here

# package: conda_kapsel

# platform:
#   - win-32
#   - win-64

# engine:
#   - python=2.7
#   - python=3.5

# install:
#   # win32 build system doesn't seem to have psutil
#   - conda install -y -q pip psutil
#   - pip install pep257 yapf==0.6.2 pytest-xdist flake8
#   - conda install -y -q pycrypto bcrypt ipython-notebook bokeh ruamel_yaml coverage beautifulsoup4 tornado pytest pytest-cov anaconda-client requests

# test:
#   - python setup.py test

# before_script:
#   - conda info
#   - python -V

# iotimeout: 600

---
platform: linux-64
engine: python=2.7

script:
  - echo "*** UPDATING CONDA BUILD"
  - conda update -n root conda-build
  - echo "*** BUILDING CONDA PACKAGES"
  - LANG=en_US.UTF-8 python setup.py conda_package
  - echo "*** LISTING BUILT STUFF"
  - ls -R build/packages
  - echo "*** DONE WITH SCRIPT SECTION"

build_targets: build/packages/*/*.tar.bz2
